# Generated by Django 2.1.15 on 2020-09-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EBUYRFQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.TextField(blank=True)),
                ('info_source', models.TextField(blank=True)),
                ('last_run', models.TextField(blank=True)),
                ('tables_count', models.CharField(max_length=60)),
                ('total_run_time', models.DateTimeField(blank=True)),
                ('status', models.TextField(blank=True)),
                ('current_status', models.TextField(blank=True)),
                ('log_error', models.TextField(blank=True)),
                ('count', models.TextField(blank=True)),
                ('bot_name', models.TextField(default='bot_name')),
            ],
        ),
    ]
